version: "3.9"
services:
  nats:
    image: nats:2.10
    ports: [ "4222:4222" ]
  pyracing_core:
    build: .
    environment:
      NATS_URL: nats://nats:4222
    depends_on: [ nats ]
  # Removed obsolete mcp_service and director_agent containers (FastMCP now launched via dev tooling / host process)
